### ISSUE TITLE
Dev Service not working in devpreview/devpreview-us latest

### ISSUE THREAD

**Issue by tfenster** [Microsoft/nav-docker#18]
If I start an instance of navdocker.azurecr.io/dynamics-nav:devpreview or navdocker.azurecr.io/dynamics-nav:devpreview-us everything is fine but the Dev Service seems not to work. It should be configured
```
[863ef91b832d...]: PS C:\Users\ContainerAdministrator\Documents> (Get-NAVServerConfiguration NAV -AsXml).configuration.appSettings.add | where-object key -match "Developer*"

key                         value
---                         -----
DeveloperServicesPort       7049
DeveloperServicesEnabled    true
DeveloperServicesSSLEnabled false
```
But if I try to connect I get "connection refused" and if I check netstat I see the following:
```
[863ef91b832d...]: PS C:\Users\ContainerAdministrator\Documents> netstat -a

Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:80             d365-infoma:0          LISTENING
  TCP    0.0.0.0:135            d365-infoma:0          LISTENING
  TCP    0.0.0.0:1433           d365-infoma:0          LISTENING
  TCP    0.0.0.0:5985           d365-infoma:0          LISTENING
  TCP    0.0.0.0:7045           d365-infoma:0          LISTENING
  TCP    0.0.0.0:7046           d365-infoma:0          LISTENING
  TCP    0.0.0.0:7047           d365-infoma:0          LISTENING
  TCP    0.0.0.0:7048           d365-infoma:0          LISTENING
  TCP    0.0.0.0:8080           d365-infoma:0          LISTENING
...
  TCP    [::]:80                d365-infoma:0          LISTENING
  TCP    [::]:135               d365-infoma:0          LISTENING
  TCP    [::]:1433              d365-infoma:0          LISTENING
  TCP    [::]:5985              d365-infoma:0          LISTENING
  TCP    [::]:7045              d365-infoma:0          LISTENING
  TCP    [::]:7046              d365-infoma:0          LISTENING
  TCP    [::]:7047              d365-infoma:0          LISTENING
  TCP    [::]:7048              d365-infoma:0          LISTENING
  TCP    [::]:8080              d365-infoma:0          LISTENING
...
  TCP    [::1]:7045             d365-infoma:49238      ESTABLISHED
  TCP    [::1]:49209            d365-infoma:7045       TIME_WAIT
  TCP    [::1]:49238            d365-infoma:7045       ESTABLISHED
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5355           *:*
  UDP    [::]:5353              *:*
  UDP    [::]:5355              *:*
```

If I try to restart it through Set-NAVServerInstance NAV -Restart I get
```
Set-NAVServerInstance : ServerInstance 'MicrosoftDynamicsNavServer$NAV' failed to reach  status 'Stopped' on this
server due to the following error: 'The service cannot accept control messages at this time'. Additional information
may be in the event log of the server.
    + CategoryInfo          : NotSpecified: (0:Int32) [Set-NAVServerInstance], NavServerInstanceException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$NAV,Microsoft.Dynamics.Nav.Management.Cmdlets.SetNavServerIns
   tance
```
And the log shows
```
Category           : (0)
CategoryNumber     : 0
ReplacementStrings : {Type: Microsoft.Dynamics.Nav.Management.Exceptions.NavServerInstanceException
                     SuppressMessage: False
                     DiagnosticsSuppress: False
                     SuppressExceptionCreatedEvent: False
                     FatalityScope: None
                     Message: <ii>ServerInstance 'MicrosoftDynamicsNavServer$NAV' failed to reach  status 'Stopped' on
                     this server due to the following error: 'The service cannot accept control messages at this
                     time'. Additional information may be in the event log of the server.</ii>
                     StackTrace:
                          at Microsoft.Dynamics.Nav.Management.NavCommand.WriteError(Exception exception,
                     ErrorCategory category, Object target, Boolean rethrow)
                          at Microsoft.Dynamics.Nav.Management.NavCommand.WriteError(Exception exception,
                     ErrorCategory category, Object target)
                          at Microsoft.Dynamics.Nav.Management.NavServerInstanceBase.StopService(String
                     serverInstanceName)
                          at Microsoft.Dynamics.Nav.Management.Cmdlets.SetNavServerInstance.InternalProcessRecord()
                          at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()
                     Source: Microsoft.Dynamics.Nav.Management
                     HResult: -2146233088
                     ----------------------------------
                     Type: System.ComponentModel.Win32Exception
                     NativeErrorCode: 1061
                     ErrorCode: -2147467259
                     Message: <ii>The service cannot accept control messages at this time</ii>
                     HResult: -2147467259
                     }
Source             : Microsoft.Dynamics.Nav.Management.dll
TimeGenerated      : 8/14/2017 8:55:02 AM
TimeWritten        : 8/14/2017 8:55:02 AM
UserName           :
```

I used the following to start the instance:
```
docker run -e username=tfenster -e password="StrengGeheim123!" --name d365-infoma --hostname d365-infoma -p 443:443 -p 1433:1433 -p 80:80 -p 7045-7049:7045-7049 -p 8080:8080 -d -e WindowsAuth=Y -e ACCEPT_EULA=Y navdocker.azurecr.io/dynamics-nav:devpreview-us
```

Am I missing anything?

**Comment by freddydk** [comment]
Just tried to spin one up using

docker run -e accept_eula=Y -e useSSL=N navdocker.azurecr.io/dynamics-nav:devpreview-us

Works fine:

  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:80             4afe331ee64d:0         LISTENING
  TCP    0.0.0.0:135            4afe331ee64d:0         LISTENING
  TCP    0.0.0.0:1433           4afe331ee64d:0         LISTENING
  TCP    0.0.0.0:5985           4afe331ee64d:0         LISTENING
  TCP    0.0.0.0:7045           4afe331ee64d:0         LISTENING
  TCP    0.0.0.0:7046           4afe331ee64d:0         LISTENING
  TCP    0.0.0.0:7047           4afe331ee64d:0         LISTENING
  TCP    0.0.0.0:7048           4afe331ee64d:0         LISTENING
  TCP    0.0.0.0:7049           4afe331ee64d:0         LISTENING
  TCP    0.0.0.0:8080           4afe331ee64d:0         LISTENING

Will try Windows Auth.

**Comment by tfenster** [comment]
Without Win Auth it works for me as well. But not with Win Auth

**Comment by tfenster** [comment]
Funny. If I 
```
docker run -e username=tfenster -e password="StrengGeheim123!" -d -e WindowsAuth=Y -e ACCEPT_EULA=Y -e useSSL=N navdocker.azurecr.io/dynamics-nav:devpreview
```
I get
```
[6b5761b1b2ef...]: PS C:\Users\ContainerAdministrator\Documents> netstat -a

Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:80             6b5761b1b2ef:0         LISTENING
  TCP    0.0.0.0:135            6b5761b1b2ef:0         LISTENING
  TCP    0.0.0.0:1433           6b5761b1b2ef:0         LISTENING
  TCP    0.0.0.0:5985           6b5761b1b2ef:0         LISTENING
  TCP    0.0.0.0:7045           6b5761b1b2ef:0         LISTENING
  TCP    0.0.0.0:7046           6b5761b1b2ef:0         LISTENING
  TCP    0.0.0.0:7047           6b5761b1b2ef:0         LISTENING
  TCP    0.0.0.0:7048           6b5761b1b2ef:0         LISTENING
  TCP    0.0.0.0:8080           6b5761b1b2ef:0         LISTENING
  TCP    0.0.0.0:47001          6b5761b1b2ef:0         LISTENING
  TCP    0.0.0.0:49152          6b5761b1b2ef:0         LISTENING
  TCP    0.0.0.0:49153          6b5761b1b2ef:0         LISTENING
  TCP    0.0.0.0:49154          6b5761b1b2ef:0         LISTENING
  TCP    0.0.0.0:49157          6b5761b1b2ef:0         LISTENING
  TCP    0.0.0.0:49158          6b5761b1b2ef:0         LISTENING
  TCP    127.0.0.1:1434         6b5761b1b2ef:0         LISTENING
  TCP    172.31.98.51:49155     40.77.226.250:https    ESTABLISHED
  TCP    172.31.98.51:49156     a2-16-64-168:http      ESTABLISHED
  TCP    172.31.98.51:49166     a95-101-89-243:http    ESTABLISHED
  TCP    172.31.98.51:49174     a95-101-89-243:http    ESTABLISHED
  TCP    [::]:80                6b5761b1b2ef:0         LISTENING
  TCP    [::]:135               6b5761b1b2ef:0         LISTENING
  TCP    [::]:1433              6b5761b1b2ef:0         LISTENING
  TCP    [::]:5985              6b5761b1b2ef:0         LISTENING
  TCP    [::]:7045              6b5761b1b2ef:0         LISTENING
  TCP    [::]:7046              6b5761b1b2ef:0         LISTENING
  TCP    [::]:7047              6b5761b1b2ef:0         LISTENING
  TCP    [::]:7048              6b5761b1b2ef:0         LISTENING
  TCP    [::]:8080              6b5761b1b2ef:0         LISTENING
  TCP    [::]:47001             6b5761b1b2ef:0         LISTENING
  TCP    [::]:49152             6b5761b1b2ef:0         LISTENING
  TCP    [::]:49153             6b5761b1b2ef:0         LISTENING
  TCP    [::]:49154             6b5761b1b2ef:0         LISTENING
  TCP    [::]:49157             6b5761b1b2ef:0         LISTENING
  TCP    [::]:49158             6b5761b1b2ef:0         LISTENING
  TCP    [::1]:1434             6b5761b1b2ef:0         LISTENING
  TCP    [::1]:7045             6b5761b1b2ef:49160     ESTABLISHED
  TCP    [::1]:7045             6b5761b1b2ef:49163     ESTABLISHED
  TCP    [::1]:49160            6b5761b1b2ef:7045      ESTABLISHED
  TCP    [::1]:49163            6b5761b1b2ef:7045      ESTABLISHED
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5355           *:*
  UDP    [::]:5353              *:*
  UDP    [::]:5355              *:*
```
Is that exactly the run command you are using or is still anything different?

**Comment by freddydk** [comment]
Copied the command and ran the same - I get 7049 in netstat (and a user called tfenster with a very secret password)

**Comment by tfenster** [comment]
Ok, then I'll just accept that something might be wrong in my environment... (and have fun with my password, obviously not the real one :) )
