### ISSUE TITLE
ClickOnce Remote name could not be resolved

### ISSUE THREAD

**Issue by worldofthenavcraft** [Microsoft/nav-docker#181]
Hi
I created azure container like this:

az container create --resource-group ***
--name *** --image indrek.azurecr.io/dynamics-nav:2018 
--registry-login-server *** --registry-username ***
--registry-password ***
-os-type Windows 
--ip-address public --cpu 2 --memory 4 --dns-name-label nav2018w1democurrent
--ports 443 7046 7048 7049 8080 
--environment-variables ACCEPT_EULA=Y username=*** password=*** ClickOnce=Y

Azure Container Registry indrek.azurecr.io/dynamics-nav:2018 based for Microsft Nav repo Microsoft/dynamics-nav:2018

When i run ClickOne istallation  from my local laptop i got error file like this:

PLATFORM VERSION INFO
	Windows 			: 10.0.16299.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2556.0 built by: NET471REL1
	clr.dll 			: 4.7.2633.0 built by: NET471REL1LAST_C
	dfdll.dll 			: 4.7.2556.0 built by: NET471REL1
	dfshim.dll 			: 10.0.16299.15 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/indrekt/Downloads/Microsoft.Dynamics.Nav.Client%20(3).application
	Deployment Provider url		: http://6f0fc16bb646:8080/NAV/Win/Deployment/Microsoft.Dynamics.Nav.Client.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\indrekt\Downloads\Microsoft.Dynamics.Nav.Client (3).application resulted in exception. Following failure messages were detected:
		+ Downloading http://6f0fc16bb646:8080/NAV/Win/Deployment/Microsoft.Dynamics.Nav.Client.application did not succeed.
		+ The remote name could not be resolved: '6f0fc16bb646'

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [10.04.2018 22:41:00] : Activation of C:\Users\indrekt\Downloads\Microsoft.Dynamics.Nav.Client (3).application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [10.04.2018 22:41:03] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading http://6f0fc16bb646:8080/NAV/Win/Deployment/Microsoft.Dynamics.Nav.Client.application did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirect(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.FollowDeploymentProviderUri(SubscriptionStore subStore, AssemblyManifest& deployment, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The remote name could not be resolved: '6f0fc16bb646'
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

On some reason it cant solve IP address because error pointing to host name 6f0fc16bb646 but my nav container have public IP.

Br,
Indrek

**Comment by freddydk** [comment]
I think this happens when you use Google Chrome, not sure why.
Could you try Edge or IE?

**Comment by worldofthenavcraft** [comment]
Same

Error are bit of diferent:

PLATFORM VERSION INFO
	Windows 			: 10.0.16299.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2556.0 built by: NET471REL1
	clr.dll 			: 4.7.2633.0 built by: NET471REL1LAST_C
	dfdll.dll 			: 4.7.2556.0 built by: NET471REL1
	dfshim.dll 			: 10.0.16299.15 (WinBuild.160101.0800)

SOURCES
	Deployment url			: http://51.145.158.242:8080/NAV/Win/Deployment/Microsoft.Dynamics.Nav.Client.application
						Server		: Microsoft-IIS/10.0
						X-Powered-By	: ASP.NET
	Deployment Provider url		: http://6f0fc16bb646:8080/NAV/Win/Deployment/Microsoft.Dynamics.Nav.Client.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://51.145.158.242:8080/NAV/Win/Deployment/Microsoft.Dynamics.Nav.Client.application resulted in exception. Following failure messages were detected:
		+ Downloading http://6f0fc16bb646:8080/NAV/Win/Deployment/Microsoft.Dynamics.Nav.Client.application did not succeed.
		+ The remote name could not be resolved: '6f0fc16bb646'

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [10.04.2018 23:11:24] : Activation of http://51.145.158.242:8080/NAV/Win/Deployment/Microsoft.Dynamics.Nav.Client.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [10.04.2018 23:11:26] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading http://6f0fc16bb646:8080/NAV/Win/Deployment/Microsoft.Dynamics.Nav.Client.application did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirect(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.FollowDeploymentProviderUri(SubscriptionStore subStore, AssemblyManifest& deployment, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The remote name could not be resolved: '6f0fc16bb646'
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by worldofthenavcraft** [comment]
Ok, I made last try with http://nav2018w1democurrent.westeurope.azurecontainer.io:8080/NAV still same result or you  think it should working when i am make a and cname record form my own domain against container itself? 👍

**Comment by freddydk** [comment]
if that is your public dns name you should add an environment variable:

--environment-variables PublicDnsName=nav2018w1democurrent.westeurope.azurecontainer.io

that might do it.

**Comment by worldofthenavcraft** [comment]
Sir I would like to report:
Site: http://nav2018w1democurrent.westeurope.azurecontainer.io:8080/NAV/ is up and running and allowing ClickOnce installation with my favorite browser (Google Chrome :))

I would suggest you to update https://github.com/Microsoft/nav-docker/blob/master/HOWTO.md on section Adding ClickOnce deployment of the Windows Client. I feel it is useful to add some explanation about --environment-variables PublicDnsName.

Also it is good idea to add extra section about list of useful environment variables with short explanations.

Tank you for supporting!

**Comment by freddydk** [comment]
Good to hear, thanks

**Comment by worldofthenavcraft** [comment]
![c_side_clickonce](https://user-images.githubusercontent.com/38262971/38680892-187100b0-3e70-11e8-95ea-901b65074e2a.png)

i found that there are issue with C Side client with ClickOnce installation hosted by Azure Container Instance
When I try to run table directly from development environment then it points to containerized hostname   e.g: 94abb3c9a34a instead value of PublicDnsName. Just added Picture to more explain. 
Can we somehow change that behavior when deploying NAV docker container to Azure Container Instance?

**Comment by freddydk** [comment]
Using the publicdnsname in CSIDE will most of the time be wrong.
Most VMs etc. will not have a pen SQL port and as such it will fail.
