### ISSUE TITLE
ClickOnce FinSQL missing libraries

### ISSUE THREAD

**Issue by megel** [Microsoft/nav-docker#29]
When I use the FinSQL ClickOnce from docker container "devpreview" and I try to compile an object I get the following error:
![grafik](https://user-images.githubusercontent.com/15800069/29455157-61370bca-8410-11e7-9af0-8f65c633af07.png)

Synchronize Schema is also impossible.

Found some log information (maybe from the action I have tried):
```
TimeGenerated : 8/18/2017 12:42:14 PM
EntryType     : Warning
Message       : Server instance: NAV
                Category: Runtime
                ClientSessionId: 00000000-0000-0000-0000-000000000000
                ClientActivityId: 00000000-0000-0000-0000-000000000000
                ServerSessionUniqueId: e7b2f268-59e9-4796-81b0-af93cf5699af
                ServerActivityId: 885749d0-1cc3-4513-9a41-c10bb18345df
                EventTime: 08/18/2017 10:42:14
                Message <ii>(NavNCLDialogException): <ii>Exception of type 'Mic
                rosoft.Dynamics.Nav.Types.Exceptions.NavNCLDialogException'
                was thrown.
                ExceptionStackTrace:
                   at Microsoft.Dynamics.Nav.Runtime.NavDialog.ALError(Guid
                automationId, String message)
                   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit5330.C
                heckOrEnableCRMConnection_Scope.OnRun()
                   at Filter.InvokeWithFilter(NavMethodScope )
                   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
                   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit5330.C
                heckOrEnableCRMConnection()
                   at Filter.InvokeWithFilter(NavMethodScope )
                   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
                   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit5330.O
                nRun(INavRecordHandle εrec)
                   at
                Microsoft.Dynamics.Nav.Runtime.NavCodeunit.DoRun(DataError
                errorLevel, NavRecord record)
                   at Microsoft.Dynamics.Nav.Runtime.NavCodeunit.RunCodeunit(Da
                taError errorLevel, Int32 objectId)
                   at Filter.InvokeWithFilter(NavMethodScope )
                   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
                   at
                Microsoft.Dynamics.Nav.BusinessApplication.Page5353.OnInit()
                   at Microsoft.Dynamics.Nav.Runtime.NavForm.InitializeForm()
                   at Microsoft.Dynamics.Nav.BusinessApplication.Page5353.__Con
                struct(ITreeObject parent, NavRecord record)
                   at Microsoft.Dynamics.Nav.Runtime.NCLMetaForm.CreateObjectIn
                stance(NavRecord record)
                   at Microsoft.Dynamics.Nav.Runtime.NCLMetaForm.CreateObjectIn
                stance(String personalizationId)
                   at
                Microsoft.Dynamics.Nav.Service.NsDataAccess.Create(ITreeObject
                parent, NavRecordState state, Boolean instantiateNewForm, Guid
                parentFormHandle, String parentControlName, Boolean&
                instantiatedForm)
                   at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.Registrate
                DataAccess()
                   at
                Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.Open(NavSession
                session)
                   at Microsoft.Dynamics.Nav.Service.NSService.OpenForm(OpenFor
                mRequest form)
                   at SyncInvokeOpenForm(Object , Object[] , Object[] )
                   at
                System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object
                instance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Ru
                nInTransactionCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass24_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Tr
                ansientErrorRetryCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass24_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Er
                rorMappingCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                CallerStackTrace:
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Er
                rorMappingCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass24_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Pu
                shPopCombinator(ServiceOperation innerOperation, NSServiceBase
                serviceInstance, MethodBase syncMethod, Object[] inputs,
                Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass24_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Tr
                aceScopeCombinator(Category telemetryCategory,
                ServiceOperation innerOperation, NSServiceBase
                serviceInstance, MethodBase syncMethod, Object[] inputs,
                Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass24_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass10_0.<PerformanceCounterCombinator>b__0()
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Pe
                rformanceCounterCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass24_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Tl
                sClearCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass24_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.In
                voke(Object instance, Object[] inputs, Object[]& outputs)
                   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.I
                nvokeBegin(MessageRpc& rpc)
                   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.P
                rocessMessage5(MessageRpc& rpc)
                   at
                System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean
                isOperationContextSet)
                   at System.ServiceModel.Dispatcher.MessageRpc.Wrapper.Resume(
                Boolean& alreadyResumedNoLock)
                   at System.ServiceModel.Dispatcher.ThreadBehavior.ResumeProce
                ssing(IResumeMessageRpc resume)
                   at Microsoft.Dynamics.Nav.Runtime.NavSynchronizationContext.
                <>c__DisplayClass1_0.<ClearThreadLocalStorageDelegate>b__0(Obje
                ct state)
                   at
                System.Threading.ExecutionContext.RunInternal(ExecutionContext
                executionContext, ContextCallback callback, Object state,
                Boolean preserveSyncCtx)
                   at System.Threading.ExecutionContext.Run(ExecutionContext
                executionContext, ContextCallback callback, Object state,
                Boolean preserveSyncCtx)
                   at System.Threading.QueueUserWorkItemCallback.System.Threadi
                ng.IThreadPoolWorkItem.ExecuteWorkItem()
                   at System.Threading.ThreadPoolWorkQueue.Dispatch()

                </ii></ii>
                ProcessId: 792
                Tag: 00000HC
                ThreadId: 8
                CounterInformation:

```

The next problem by using FinSQL is, the intellisence is not working (also missing libraries?).

**Comment by freddydk** [comment]
I will have a look at this and fix it.

**Comment by freddydk** [comment]
As a temporary fix, if you create a folder on the host c: drive called myfolder and create a script in that called SetupClickOnceDirectory.ps1 with this content:

. (Join-Path $runPath $MyInvocation.MyCommand.Name)

Copy-Item "$roleTailoredClientFolder\Microsoft.Dynamics.Nav.Language.dll" -Destination "$ClickOnceApplicationFilesDirectoryFinsql"

and then use -v c:\myfolder:c:\run\my in your docker run statement, you will get nav.language included in your finsql clickonce deployment.
I have just tested this and it seems to work (also source highlighting). I will add the nav.language to the base SetupClickOnceDirectory and check it in.

**Comment by freddydk** [comment]
Fixed, will rebuild images within the next days
