### ISSUE TITLE
Fatal error during metadata load 

### ISSUE THREAD

**Issue by rdebath** [microsoft/nav-docker#435]
I just received this error from a "NextSaaS" docker database and thought I should report it.
Now, I expect this is just a transient error (hopefully avoidable) from the publish section of the build process so I should try the next build ...

But, what if it happens in Live; is there any way to force a recompile of an app file that has been "published" into the database? 
NB; this is Base App so unpublishing (even though it works) it is probably a really bad idea.

```
Server instance: BC150Next
Category: Extensions
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 3dcea990-b1a6-41e3-9480-234ef48eba46
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 9ec03fdf-95b7-4c4e-8d8e-6bf23ad33e48
EventTime: 12/10/2019 11:45:09
Message Fatal error during metadata load -- Type:Query; Id:5480; MetadataGroup:3; MetadataLoaded:False; CLRLoaded:False; ThreadGroup:0
ProcessId: 29504
Tag: 00007YQ
ThreadId: 8
CounterInformation: 
CustomParameters: 00000000-0000-0000-0000-000000000000

Server instance: BC150Next
Category: Extensions
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 3dcea990-b1a6-41e3-9480-234ef48eba46
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 9ec03fdf-95b7-4c4e-8d8e-6bf23ad33e48
EventTime: 12/10/2019 11:45:09
Message (NavNCLMetadataObjectNotFoundException): RootException: NavNCLMetadataObjectNotFoundException
Object of type Table with ID 21 could not be found.
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Boolean onlySearchCache, Int32 appGroupId)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObject(ApplicationObjectId appObjectId, Int32 appGroupId, Boolean requireCompiled, Boolean onlySearchCache)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaTableById(Int32 tableId, Int32 appGroupId, Boolean requireCompiled, Boolean onlySearchCache)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQueryDataItem.ResolveMetaTable(NavAppGroup appGroup)
   at Microsoft.Dynamics.Nav.Runtime.AppGroupAwareLookup`1.GetReferenceUsingSpecificAppGroup(NavAppGroup appGroup)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.CreateTableFiltersAndMarksFromDataItemFieldFilters(NCLMetaQueryDataItem dataItemBeingCreated, List`1 fieldFilters, Boolean allowExpressionEvaluation, Boolean& tableFilterHasVariables)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.<>c__DisplayClass67_1.<CreateDataItemsFromDesignMetadata>b__1(NCLMetaQueryDataItem dataItemBeingCreated)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQueryDataItem..ctor(NCLMetaQueryDefinition parentQueryDefinition, DataItemLinkType dataItemLinkType, Int32 tableNo, DataLockState lockState, String name, Func`2 queryColumnsCreator, Func`2 tableFiltersAndMarksCreator, Func`2 dataItemLinksCreator, List`1 metaQueryFieldFilters, Int32 appGroup)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.CreateDataItemsFromDesignMetadata(NCLMetaQueryDefinition parentQueryDefinition, MetaQuery metaQuery, Boolean allowExpressionEvaluation, Boolean& tableFilterHasVariables)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.<>c__DisplayClass68_1.<ParseMetadata>b__0(NCLMetaQueryDefinition queryDefinitionBeingCreated)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQueryDefinition..ctor(NCLMetaQueryDataItem parentDataItem, Int32 topRows, Func`2 dataItemsCreator, Func`2 orderBysCreator)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.ParseMetadata(MetaQuery metaQuery, Boolean allowExpressionEvaluation)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.LoadMetadata()
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.Populate()
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Boolean onlySearchCache, Int32 appGroupId)
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Boolean onlySearchCache, Int32 appGroupId)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObject(ApplicationObjectId appObjectId, Int32 appGroupId, Boolean requireCompiled, Boolean onlySearchCache)
   at Microsoft.Dynamics.Nav.Runtime.ApiWebServiceEntryHelper.GetAllVersions(ObjectType objectType, Int32 objectId, PackageId packageId, NavAppGroup group, HashSet`1 paths, Boolean throwOnEndpointDuplicate)
   at Microsoft.Dynamics.Nav.Runtime.ApiWebServiceEntryHelper.GetEntriesFromNavApp(NavTenant tenant, HashSet`1 paths)
   at Microsoft.Dynamics.Nav.Runtime.WebServiceHelper.GetApiWebServices(NavTenant tenant)
   at Microsoft.Dynamics.Nav.Service.Api.ApiRouteManager.ConfigureCommonRoutesForAllTenants()
   at Microsoft.Dynamics.Nav.Service.Api.GraphApiHost.ConfigureHost(WebApiHost context, IAppBuilder builder, Category telemetryCategory, AuthenticationSchemes authenticationScheme, DelegatingHandler handler)
   at Microsoft.Dynamics.Nav.Service.WebApi.WebApiHost.<Open>b__31_0(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Dynamics.Nav.Service.WebApi.WebApiHost.Open(String machineName, ServerUserSettings settings)
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.StartOwinServices(ServerUserSettings settings)
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.StartAllServices(ServerUserSettings settings)
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.Start(String commandLineServiceInstanceName)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


ProcessId: 29504
Tag: 00007YR
ThreadId: 8
CounterInformation: 
CustomParameters: 48499132-0250-408c-9f35-eed08daf2826

Server instance: BC150Next
Category: Extensions
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 3dcea990-b1a6-41e3-9480-234ef48eba46
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 9ec03fdf-95b7-4c4e-8d8e-6bf23ad33e48
EventTime: 12/10/2019 11:45:09
Message (NavNCLMetadataObjectNotFoundException): This message had personal data removed. The original may still be in transient telemetry. Find it using the transientTelemetryId.
RootException: NavNCLMetadataObjectNotFoundException
Message not shown because the NavBaseException(string, Exception, bool) constructor was used.
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Boolean onlySearchCache, Int32 appGroupId)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObject(ApplicationObjectId appObjectId, Int32 appGroupId, Boolean requireCompiled, Boolean onlySearchCache)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaTableById(Int32 tableId, Int32 appGroupId, Boolean requireCompiled, Boolean onlySearchCache)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQueryDataItem.ResolveMetaTable(NavAppGroup appGroup)
   at Microsoft.Dynamics.Nav.Runtime.AppGroupAwareLookup`1.GetReferenceUsingSpecificAppGroup(NavAppGroup appGroup)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.CreateTableFiltersAndMarksFromDataItemFieldFilters(NCLMetaQueryDataItem dataItemBeingCreated, List`1 fieldFilters, Boolean allowExpressionEvaluation, Boolean& tableFilterHasVariables)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.<>c__DisplayClass67_1.<CreateDataItemsFromDesignMetadata>b__1(NCLMetaQueryDataItem dataItemBeingCreated)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQueryDataItem..ctor(NCLMetaQueryDefinition parentQueryDefinition, DataItemLinkType dataItemLinkType, Int32 tableNo, DataLockState lockState, String name, Func`2 queryColumnsCreator, Func`2 tableFiltersAndMarksCreator, Func`2 dataItemLinksCreator, List`1 metaQueryFieldFilters, Int32 appGroup)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.CreateDataItemsFromDesignMetadata(NCLMetaQueryDefinition parentQueryDefinition, MetaQuery metaQuery, Boolean allowExpressionEvaluation, Boolean& tableFilterHasVariables)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.<>c__DisplayClass68_1.<ParseMetadata>b__0(NCLMetaQueryDefinition queryDefinitionBeingCreated)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQueryDefinition..ctor(NCLMetaQueryDataItem parentDataItem, Int32 topRows, Func`2 dataItemsCreator, Func`2 orderBysCreator)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.ParseMetadata(MetaQuery metaQuery, Boolean allowExpressionEvaluation)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.LoadMetadata()
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.Populate()
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Boolean onlySearchCache, Int32 appGroupId)
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Boolean onlySearchCache, Int32 appGroupId)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObject(ApplicationObjectId appObjectId, Int32 appGroupId, Boolean requireCompiled, Boolean onlySearchCache)
   at Microsoft.Dynamics.Nav.Runtime.ApiWebServiceEntryHelper.GetAllVersions(ObjectType objectType, Int32 objectId, PackageId packageId, NavAppGroup group, HashSet`1 paths, Boolean throwOnEndpointDuplicate)
   at Microsoft.Dynamics.Nav.Runtime.ApiWebServiceEntryHelper.GetEntriesFromNavApp(NavTenant tenant, HashSet`1 paths)
   at Microsoft.Dynamics.Nav.Runtime.WebServiceHelper.GetApiWebServices(NavTenant tenant)
   at Microsoft.Dynamics.Nav.Service.Api.ApiRouteManager.ConfigureCommonRoutesForAllTenants()
   at Microsoft.Dynamics.Nav.Service.Api.GraphApiHost.ConfigureHost(WebApiHost context, IAppBuilder builder, Category telemetryCategory, AuthenticationSchemes authenticationScheme, DelegatingHandler handler)
   at Microsoft.Dynamics.Nav.Service.WebApi.WebApiHost.<Open>b__31_0(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Dynamics.Nav.Service.WebApi.WebApiHost.Open(String machineName, ServerUserSettings settings)
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.StartOwinServices(ServerUserSettings settings)
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.StartAllServices(ServerUserSettings settings)
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.Start(String commandLineServiceInstanceName)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


ProcessId: 29504
Tag: 00007YR
ThreadId: 8
CounterInformation: 
CustomParameters: 48499132-0250-408c-9f35-eed08daf2826
```

**Comment by freddydk** [comment]
You cannot recompile and you never need to. The way Business Central stores metadata today is significantly different and cannot be compared to how things were in NAV.

Having said that, if I look in the eventlog of my latest shipped sandbox container - I have the same error, but the container works fine - I assume that this is part of initialization or like.

Will see if I can figure out why.

**Comment by freddydk** [comment]
I found that all of these entries are from API Services.
If I disable API Services, no event log entries are present.
I will check with the team working on API Services.

**Comment by rdebath** [comment]
Except when I did _recompile_ the `Base Application` the error went away.
I did it the obvious way by unpublishing then republishing every extension.

**Comment by freddydk** [comment]
The error stems from API Services - it is a timing issue when you start the container.
Start the container without API Services and the "error" goes away.
"error" in quotes because the error doesn't block anything.
The isse will be fixed in the platform.
