### ISSUE TITLE
ClickOnce finsql EntryPoint

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/nav-docker#442]
when executing a clickonce deplyoments for the old dev client (finsql) an error occurs.
For unknown reasons the EntryPoint [is not replaced correctly](https://github.com/microsoft/nav-docker/blob/master/generic/Run/110/SetupClickOnce.ps1#L116) and the application cannot be installed.

Tested with Image: mcr.microsoft.com/dynamicsnav:2018-cu23 via aka.ms/getnav

Part of Finsql.exe.manifest
```
  <entryPoint>
    <assemblyIdentity name="Microsoft.Dynamics.Nav.Client" version="11.0.0.0" publicKeyToken="31BF3856AD364E35" language="neutral" processorArchitecture="msil" />
    <commandLine file="Microsoft.Dynamics.Nav.Client.exe" parameters="" />
  </entryPoint>
```

ClickOnce Error Details:
```
PLATFORM VERSION INFO
	Windows 			: 10.0.17763.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.3190.0 built by: NET472REL1LAST_C
	clr.dll 			: 4.7.3468.0 built by: NET472REL1LAST_C
	dfdll.dll 			: 4.7.3190.0 built by: NET472REL1LAST_C
	dfshim.dll 			: 10.0.17763.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: http://***.westeurope.cloudapp.azure.com:8080/NAV/Finsql/Deployment/Finsql.application
						Server		: Microsoft-IIS/10.0
						X-Powered-By	: ASP.NET
	Deployment Provider url		: http://***.westeurope.cloudapp.azure.com:8080/NAV/Finsql/Deployment/Finsql.application

IDENTITIES
	Deployment Identity		: ***.westeurope.cloudapp.azure.com Finsql ClickOnce, Version=11.0.37606.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=x86

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://***.westeurope.cloudapp.azure.com:8080/NAV/Finsql/Deployment/Finsql.application resulted in exception. Following failure messages were detected:
		+ Exception reading manifest from http://***.westeurope.cloudapp.azure.com:8080/NAV/Finsql/Deployment/ApplicationFiles/Finsql.exe.manifest: the manifest may not be valid or the file could not be opened.
		+ Application manifest is not semantically valid.
		+ Specified <entryPoint> is not valid. Check that the path to the entrypoint is well-formed and the entrypoint exists in the deployment.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [1/30/2020 11:50:03 AM] : Activation of http://***.westeurope.cloudapp.azure.com:8080/NAV/Finsql/Deployment/Finsql.application has started.
	* [1/30/2020 11:50:03 AM] : Processing of deployment manifest has successfully completed.
	* [1/30/2020 11:50:03 AM] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [1/30/2020 11:50:04 AM] System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Exception reading manifest from http://***.westeurope.cloudapp.azure.com:8080/NAV/Finsql/Deployment/ApplicationFiles/Finsql.exe.manifest: the manifest may not be valid or the file could not be opened.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (ManifestSemanticValidation)
		- Application manifest is not semantically valid.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSemanticsForApplicationRole()
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (InvalidManifest)
		- Specified <entryPoint> is not valid. Check that the path to the entrypoint is well-formed and the entrypoint exists in the deployment.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSemanticsForApplicationRole()

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.
```

**Comment by freddydk** [comment]
Is a duplicate of this one: https://github.com/microsoft/navcontainerhelper/issues/826
(Which also contains a workaround)

**Comment by ChrisBlankDe** [comment]
Sorry. Just searched in this Repo (which is the source of the failure).

**Comment by freddydk** [comment]
No problem (and agree:-))
