### ISSUE TITLE
Unable to download C/SIDE environment and WinClient using Docker image for NAV2017-CU5

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/nav-docker#83]
I'm trying to run NAV 2017 cu5 on docker with this command on win10 localhost:

``
docker run -m 3G -e ACCEPT_EULA=Y -e UseSSL=N -e ClickOnce=Y -e auth=Windows -e username=ivand -e password=<mypassword> -v c:\myfolder:c:\run\my -e LicenseFile=c:\run\my\mylicense.flf navdocker.azurecr.io/dynamics-nav:2017-cu5
``

When using the ClickOnce link on browser to install client and C/SIDE...

![image](https://user-images.githubusercontent.com/20359384/32010150-52cd49ce-b9b1-11e7-9ac3-3b99073a96e6.png)

... I get this error:
``
Application cannot be started. Contact the application vendor.
``

With this log in details:

````
`PLATFORM VERSION INFO
	Windows 			: 10.0.15063.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2046.0 built by: NET47REL1
	clr.dll 			: 4.7.2115.0 built by: NET47REL1LAST
	dfdll.dll 			: 4.7.2046.0 built by: NET47REL1
	dfshim.dll 			: 10.0.15063.0 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/ivand/Desktop/TEMP/Microsoft.Dynamics.Nav.Client.application

IDENTITIES
	Deployment Identity		: 15ed60b1ae92 ClickOnce, Version=10.0.16177.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\ivand\Desktop\TEMP\Microsoft.Dynamics.Nav.Client.application resulted in exception. Following failure messages were detected:
		+ Deployment and application do not have matching security zones.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [25.10.2017. 18.22.18] : Activation of C:\Users\ivand\Desktop\TEMP\Microsoft.Dynamics.Nav.Client.application has started.
	* [25.10.2017. 18.22.18] : Processing of deployment manifest has successfully completed.
	* [25.10.2017. 18.22.18] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [25.10.2017. 18.22.18] System.Deployment.Application.InvalidDeploymentException (Zone)
		- Deployment and application do not have matching security zones.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

````

**Comment by freddydk** [comment]
I think we have seen this error on some browsers - could you try with a different browser?

**Comment by Koubek** [comment]
@ivandjordjevic You should try Internet Explorer (preferable) or eventually Edge.

**Comment by wortho** [comment]
Had the same problem today.  Clicking on the Install button in the ClickOnce Installation page using Chrome downloads the Finsql.application which then fails with the above error when you try and open it.
Clicking on the Install button in the Edge opens the ClickOnce install dialog which allows you to install.

**Comment by dejfidson** [comment]
I had the same problem in Chrome but in Edge it is working!

**Comment by ivandjordjevic** [comment]
I can confirm that IE works as well. I had problems with Chrome. Thanks for help!
